### ISSUE TITLE
Awesome open source app

### ISSUE THREAD

**Issue by matteocrippa** [matteocrippa/awesome-swift-ios#6]
@dkhamsing I was thinking now to create a new target for your `awesome-opensource-ios-app` so we can even test that and having an app for that

**Comment by matteocrippa** [comment]
@dkhamsing I noticed that the json file ( https://raw.githubusercontent.com/dkhamsing/open-source-ios-apps/master/contents.json ) for Awesome OS is slightly different from the one of Awesome swift.
Do you think we can try considering to create a new version in Awesome Swift close to your repo one and have similar features?

**Comment by dkhamsing** [comment]
Hm not sure
I think my project has a lot of extra fields.. this is making the parsing problematic ?

**Comment by matteocrippa** [comment]
Nope the parsing is not that problematic, the idea was to have a kind of "awesome-repo" json standard, so try to upgrade the actual one of `awesome-swift` to something similar to your one.

In this way we can heavily share the codebase of parsing the information, instead of creating even two different dedicated data models for each repo.

**Comment by dkhamsing** [comment]
@matteocrippa hey so can u be specific, what is different between the json files on the two projects?

**Comment by matteocrippa** [comment]
@dkhamsing the idea is to have an unique parser model inside the app, in order to do that I had to change some info inside `awesome-swift` JSON file (e.g. `category` -> `category-ids`, `homepage` -> `source`).

I created for now a converter in nodejs and now I put the file on repo, I had to keep the old one to maintain compatibility over the current released app

Updated format:
https://github.com/matteocrippa/awesome-swift/blob/master/database.json

**Comment by matteocrippa** [comment]
@dkhamsing now it works fine with both the two repos, the experience is pretty the same:

- category with filter
- sub category (if exists)
- project detail with web view inside

**Comment by dkhamsing** [comment]
hey i'm confused
will you be maintaining another json file or we should try to update contents.json?

**Comment by matteocrippa** [comment]
basically we can swap to contents.json, we will only have to update your script to create the readme in `awesome-swift` the only issue is that when we will do that the old app will stop to work.

so the idea is we have a script to quickly convert to new format, as soon as I can upload the new app (now it uses Xcode beta so I can't do that) we can do the switch.

for awesome-opensource instead we have no problem

**Comment by dkhamsing** [comment]
hmm i see

can u ping me u upload the new app


thx

**Comment by matteocrippa** [comment]
yep, I think that we will be able to upload by the end of august, usually they allow some week earlier than GM release to upload app with new iOS version

**Comment by matteocrippa** [comment]
@dkhamsing added a new GIF demo, give a look there if you noticed something that is needed to be upgraded

**Comment by dkhamsing** [comment]
looks pretty good.. the segment control is a bit glitchy.. too big?

**Comment by matteocrippa** [comment]
yep is ugly as hell, I have fixed that, but there's a huge issue in Xcode storyboard ❌ 
I managed to tweak directly in the source code instead

**Comment by matteocrippa** [comment]
here the new UI
https://github.com/matteocrippa/awesome-swift-ios/raw/master/.github/app-awesome-ios-demo.gif?raw=true

if you still see the big one, cancel cache
